### ISSUE TITLE
Overlay pops up at the end of Draft (even though it's disabled)

### ISSUE THREAD

**Issue by AnnanFay** [MtgLotusValley/LotusTracker#86]
I have completely disabled the overlay however it pops up at the end of a draft - after the last game but before I claim prizes. It hasn't appeared before this.

![image](https://user-images.githubusercontent.com/766048/52862310-e9106a80-312c-11e9-9a96-cacd16d70caf.png)

**Comment by edipo2s** [comment]
That is a feature, because the intention is that you can check and/or take a screenshot of you run result. But is a bug it ignore the "Enable player cards overlay" option

**Comment by edipo2s** [comment]
Maybe would be ever better add a option exclusively to this feature. Something like: _Show deck list at end of events_.

**Comment by AnnanFay** [comment]
Either works for me. There was also one weird time when the draft-helper scores were displayed when disabled after starting a new draft. I rechecked then unchecked the option and they went away.
